/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'faceDescriptor' : IDL.Vec(IDL.Float64),
});
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'unknown' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'status' : AttendanceStatus,
  'studentId' : IDL.Nat,
  'date' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticateFace' : IDL.Func(
      [IDL.Vec(IDL.Float64), IDL.Float64],
      [IDL.Opt(Student)],
      [],
    ),
  'countPresentOnDate' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'deleteStudent' : IDL.Func([IDL.Nat], [], []),
  'getAllAttendanceRecords' : IDL.Func(
      [],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllStudentsByName' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAttendance' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(AttendanceStatus)],
      ['query'],
    ),
  'getAttendancePrediction' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'prediction' : IDL.Text, 'attendanceRate' : IDL.Float64 })],
      ['query'],
    ),
  'getAttendanceRecordsOnDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceStats' : IDL.Func(
      [],
      [IDL.Record({ 'presentToday' : IDL.Nat, 'totalStudents' : IDL.Nat })],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
  'getStudentAttendancePercentage' : IDL.Func(
      [IDL.Nat],
      [IDL.Nat, IDL.Nat, IDL.Float64],
      ['query'],
    ),
  'getStudentAttendanceRecords' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([IDL.Nat, IDL.Text, AttendanceStatus], [], []),
  'registerStudent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Float64)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'faceDescriptor' : IDL.Vec(IDL.Float64),
  });
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'status' : AttendanceStatus,
    'studentId' : IDL.Nat,
    'date' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticateFace' : IDL.Func(
        [IDL.Vec(IDL.Float64), IDL.Float64],
        [IDL.Opt(Student)],
        [],
      ),
    'countPresentOnDate' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'deleteStudent' : IDL.Func([IDL.Nat], [], []),
    'getAllAttendanceRecords' : IDL.Func(
        [],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllStudentsByName' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAttendance' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(AttendanceStatus)],
        ['query'],
      ),
    'getAttendancePrediction' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'prediction' : IDL.Text,
            'attendanceRate' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getAttendanceRecordsOnDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceStats' : IDL.Func(
        [],
        [IDL.Record({ 'presentToday' : IDL.Nat, 'totalStudents' : IDL.Nat })],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
    'getStudentAttendancePercentage' : IDL.Func(
        [IDL.Nat],
        [IDL.Nat, IDL.Nat, IDL.Float64],
        ['query'],
      ),
    'getStudentAttendanceRecords' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([IDL.Nat, IDL.Text, AttendanceStatus], [], []),
    'registerStudent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Float64)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };