/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'status' : AttendanceStatus,
  'studentId' : bigint,
  'date' : string,
}
export type AttendanceStatus = { 'present' : null } |
  { 'unknown' : null };
export interface Student {
  'id' : bigint,
  'name' : string,
  'faceDescriptor' : Array<number>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateFace' : ActorMethod<[Array<number>, number], [] | [Student]>,
  'countPresentOnDate' : ActorMethod<[string], bigint>,
  'deleteStudent' : ActorMethod<[bigint], undefined>,
  'getAllAttendanceRecords' : ActorMethod<[], Array<AttendanceRecord>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllStudentsByName' : ActorMethod<[], Array<Student>>,
  'getAttendance' : ActorMethod<[bigint, string], [] | [AttendanceStatus]>,
  'getAttendancePrediction' : ActorMethod<
    [bigint],
    { 'prediction' : string, 'attendanceRate' : number }
  >,
  'getAttendanceRecordsOnDate' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceStats' : ActorMethod<
    [],
    { 'presentToday' : bigint, 'totalStudents' : bigint }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStudent' : ActorMethod<[bigint], [] | [Student]>,
  'getStudentAttendancePercentage' : ActorMethod<
    [bigint],
    [bigint, bigint, number]
  >,
  'getStudentAttendanceRecords' : ActorMethod<
    [bigint],
    Array<AttendanceRecord>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[bigint, string, AttendanceStatus], undefined>,
  'registerStudent' : ActorMethod<[bigint, string, Array<number>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];